### ISSUE TITLE
Different name on the commit

### ISSUE THREAD

**Issue by ajawu** [Akhigbe-E/last-session-MIS-notes#1]
You know it is not your name that is on the commit right?

**Comment by Akhigbe-E** [comment]
Yh, that's the name of the Mac I used to commit

**Comment by ajawu** [comment]
Ehh Change it now
To change name and email for a particular project
git config user.name  "Replace this with your name"
git config user.email  "Replace this text with your email"
To change name and email globally
git config user.name  --global "Replace this with your name"
git config user.email  --global "Replace this text with your email"

**Comment by Akhigbe-E** [comment]
Can I do that if I don't have access to the Mac; I don't want to pull on my PC and push again

**Comment by ajawu** [comment]
I don't know of any way you can do that, just check the name and email next time you push on a different system.
